import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/db';
import Team from '@/models/team';
import Player from '@/models/player';

const MOCK_TEAMS = [
  {
    teamName: 'Royal Warriors',
    shortName: 'RW',
    managerName: 'Shafiq R',
    managerImage: '/managers/shafiq.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/royal-warriors.jpg',
    balance: 138000,
    totalSpent: 12000,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'Golden Strikers',
    shortName: 'GS',
    managerName: 'Hameed T',
    managerImage: '/managers/hameed.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/golden-strikers.jpg',
    balance: 145000,
    totalSpent: 5000,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'Kerala Blasters Juniors',
    shortName: 'KB',
    managerName: 'Rishad K',
    managerImage: '/managers/rishad.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/kerala-blasters.jpg',
    balance: 147000,
    totalSpent: 3000,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'United Legends',
    shortName: 'UL',
    managerName: 'Sajid M',
    managerImage: '/managers/sajid.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/united-legends.jpg',
    balance: 140500,
    totalSpent: 9500,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'Thunder Boys',
    shortName: 'TB',
    managerName: 'Mubashir C',
    managerImage: '/managers/mubashir.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/thunder-boys.jpg',
    balance: 130000,
    totalSpent: 20000,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'Malabar FC',
    shortName: 'MF',
    managerName: 'Jaleel P',
    managerImage: '/managers/jaleel.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/malabar-fc.jpg',
    balance: 142500,
    totalSpent: 7500,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'Fc Panayi',
    shortName: 'FCP',
    managerName: 'Aslam K',
    managerImage: '/managers/aslam.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/fc-panayi.jpg',
    balance: 149500,
    totalSpent: 500,
    remainingSlots: 10,
    buyedPlayers: [],
  },
  {
    teamName: 'Soccer Kings',
    shortName: 'SK',
    managerName: 'Faisal H',
    managerImage: '/managers/faisal.png',
    logo: '/teams/default.png',
    coverImage: '/teams/covers/soccer-kings.jpg',
    balance: 125000,
    totalSpent: 25000,
    remainingSlots: 10,
    buyedPlayers: [],
  },
];

const MOCK_PLAYERS = [
  {
    playerName: 'Asif K. P.',
    position: 'STRIKER',
    category: 'ICON',
    phoneNumber: '9876543210',
    age: 24,
    place: 'Kottayam',
    photo: '/players/asif.png',
    basePrice: 50000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Vineeth C. K.',
    position: 'MIDFIELDER',
    category: 'LEGEND',
    phoneNumber: '9876543211',
    age: 31,
    place: 'Kozhikode',
    photo: '/players/vineeth.png',
    basePrice: 80000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Jithesh P. M.',
    position: 'DEFENDER',
    category: 'YOUNG',
    phoneNumber: '9876543212',
    age: 19,
    place: 'Malappuram',
    photo: '/players/jithesh.png',
    basePrice: 20000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Sharafudeen T.',
    position: 'GOALKEEPER',
    category: 'GK',
    phoneNumber: '9876543213',
    age: 26,
    place: 'Thrissur',
    photo: '/players/sharaf.png',
    basePrice: 30000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Fasil Rahman',
    position: 'LEFT_WING',
    category: 'ICON',
    phoneNumber: '9876543214',
    age: 23,
    place: 'Ernakulam',
    photo: '/players/fasil.png',
    basePrice: 60000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Rahul K. P.',
    position: 'RIGHT_WING',
    category: 'YOUNG',
    phoneNumber: '9876543215',
    age: 20,
    place: 'Palakkad',
    photo: '/players/rahul.png',
    basePrice: 35000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Anas Edathodika',
    position: 'DEFENDER',
    category: 'LEGEND',
    phoneNumber: '9876543216',
    age: 33,
    place: 'Malappuram',
    photo: '/players/anas.png',
    basePrice: 75000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Rinshad N. P.',
    position: 'MIDFIELDER',
    category: 'ICON',
    phoneNumber: '9876543217',
    age: 25,
    place: 'Kozhikode',
    photo: '/players/rinshad.png',
    basePrice: 65000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Sreejith Murali',
    position: 'GOALKEEPER',
    category: 'GK',
    phoneNumber: '9876543218',
    age: 28,
    place: 'Kannur',
    photo: '/players/sreejith.png',
    basePrice: 30000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Ashique Kuruniyan',
    position: 'LEFT_WING',
    category: 'YOUNG',
    phoneNumber: '9876543219',
    age: 22,
    place: 'Malappuram',
    photo: '/players/ashique.png',
    basePrice: 45000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Sahal Abdul Samad',
    position: 'MIDFIELDER',
    category: 'ICON',
    phoneNumber: '9876543220',
    age: 26,
    place: 'Kasaragod',
    photo: '/players/sahal.png',
    basePrice: 100000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Sujith M. S.',
    position: 'DEFENDER',
    category: 'YOUNG',
    phoneNumber: '9876543221',
    age: 21,
    place: 'Wayanad',
    photo: '/players/sujith.png',
    basePrice: 25000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Prasanth Karuthadathkuni',
    position: 'RIGHT_WING',
    category: 'LEGEND',
    phoneNumber: '9876543222',
    age: 29,
    place: 'Thrissur',
    photo: '/players/prasanth.png',
    basePrice: 55000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Gokul Gopal',
    position: 'DEFENDER',
    category: 'YOUNG',
    phoneNumber: '9876543223',
    age: 18,
    place: 'Alappuzha',
    photo: '/players/gokul.png',
    basePrice: 20000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
  {
    playerName: 'Roshan V. Giri',
    position: 'STRIKER',
    category: 'YOUNG',
    phoneNumber: '9876543224',
    age: 20,
    place: 'Kollam',
    photo: '/players/roshan.png',
    basePrice: 40000,
    soldPrice: 0,
    soldTo: null,
    isSold: false,
  },
];

export async function POST() {
  try {
    await connectToDatabase();

    // Clear existing data
    await Team.deleteMany({});
    await Player.deleteMany({});

    // Seed Teams
    const seededTeams = await Team.insertMany(MOCK_TEAMS);

    // Seed Players
    const seededPlayers = await Player.insertMany(MOCK_PLAYERS);

    return NextResponse.json({
      message: 'Database seeded successfully',
      teamsCount: seededTeams.length,
      playersCount: seededPlayers.length,
    });
  } catch (error: unknown) {
    const err = error as Error;
    return NextResponse.json({ error: err.message || 'Failed to seed database' }, { status: 500 });
  }
}
